si: false
url: https://jason-abbott.com
safe: true
title: Talk Therapy for Midlife Indie Developer
timezone: America/Boise
incremental: false
highlighter: rouge
remote_theme: pages-themes/hacker@v0.2.0
strict_front_matter: true
gist:
  noscript: false
plugins:
- jekyll-remote-theme
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge